#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEFINES_FILE="$ROOT/oauth_defines.json"
OUTPUT_FILE="$ROOT/ios/Flutter/OAuth.xcconfig"

if [[ ! -f "$DEFINES_FILE" ]]; then
  echo "Missing oauth_defines.json — copy oauth_defines.json.example first." >&2
  exit 1
fi

read_json_value() {
  local key="$1"
  python3 - "$DEFINES_FILE" "$key" <<'PY'
import json
import sys

path, key = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as handle:
    data = json.load(handle)
print(str(data.get(key, "")).strip())
PY
}

WEB_ID="$(read_json_value GOOGLE_WEB_CLIENT_ID)"
IOS_ID="$(read_json_value GOOGLE_IOS_CLIENT_ID)"

is_placeholder() {
  local value="$1"
  [[ -z "$value" ]] && return 0
  [[ "$value" == *YOUR_* ]] && return 0
  [[ "$value" != *.apps.googleusercontent.com ]] && return 0
  return 1
}

if is_placeholder "$WEB_ID" || is_placeholder "$IOS_ID"; then
  echo "oauth_defines.json still has placeholder Google client IDs." >&2
  echo "Replace YOUR_WEB_CLIENT_ID and YOUR_IOS_CLIENT_ID with real values." >&2
  exit 1
fi

IOS_PREFIX="${IOS_ID%.apps.googleusercontent.com}"
REVERSED_ID="com.googleusercontent.apps.${IOS_PREFIX}"

cat > "$OUTPUT_FILE" <<EOF
// Generated by tool/sync_oauth_config.sh — do not edit manually.
GOOGLE_IOS_CLIENT_ID=$IOS_ID
GOOGLE_IOS_REVERSED_CLIENT_ID=$REVERSED_ID
GOOGLE_WEB_CLIENT_ID=$WEB_ID
EOF

echo "Updated $OUTPUT_FILE"
